### ISSUE TITLE
Integración de SonarQube

### ISSUE THREAD

**Issue by acb1012** [acb1012/go-bees#5]
Aunque ya se cuenta con code climate y codecov entre los servicios de integración continua para evaluar la calidad del código, sería recomendable pasar también los motores de análisis de SonarQube ya que es el que utilizará el tribunal para evaluar el TFG.

https://sonarqube.com/
https://github.com/integrations/sonarqube
https://docs.travis-ci.com/user/sonarqube/

**Comment by jga1021** [comment]
davidmigloz added a commit that referenced this issue on 19 Jan 2017
@davidmigloz
Minor fixes #155

**Comment by jga1021** [comment]
davidmigloz added a commit that referenced this issue on 19 Jan 2017
@davidmigloz
Finish SonarQube integration #155
